### ISSUE TITLE
A couple questions about JSRP

### ISSUE THREAD

**Issue by rmhrisk** [alax/jsrp#10]
We have been doing a bunch of work creating security libraries in Javascript, for example :
-  node-webcrypto-ossl, a webcrypto polyfill for Node, based on OpenSSL.
-  node-webcrypto-p11, a webcrypto polyfill for Node, based on PKCS#11.
- PKIjs, an implementation of all X.509 related data structures and formats.
- XADESjs, an implementation of XMLDSIG and XADES-BES.

Anyway I have been interested in playing with SRP and stumbled across your project, I have a questions:

1) What other SRP [implementations](https://github.com/arpa2/srp-pkcs11) has this been tested with?

2) Do you imagine it would be easy to retool to be based on WebCrypto?

3) Is there a sample client/server somewhere I could start with?

Thanks for your time.

**Comment by alax** [comment]
1. It has been tested with Node-SRP from Mozilla. Although, it should be compatible with all SRP-6A libraries, see the `tests/` for more information.
2. I'm not sure which part you'd need to retool. This package only has one dependency: JSBN. Since, as I'm sure you know, JavaScript does not natively support big integers. From what I understand, WebCrypto doesn't expose any big integer primitives.
3. Yes, take a look at the README. You can pretty much just copy and paste the code, and you'll have a working implementation.

Thanks.
