### ISSUE TITLE
about M1 and M2

### ISSUE THREAD

**Issue by jackiszhp** [alax/jsrp#15]
The M1 calculation is much different from what described here: http://srp.stanford.edu/design.html

And M2 calculation, I have seen other implementations use H(A|M1|S) rather than H(A|M1|K).

I guess it will be better to describe the formula in the readme page, so people can have an idea on the exact formula.

**Comment by alax** [comment]
Regarding the M2 calculation, the RFC (https://www.ietf.org/rfc/rfc2945.txt, page 3) calls for H(A|M1|K), so that's what I use here.

As for the M1 calculation, it's the alternate formula described on the Wikipedia page. I initially chose it to be compatible with Mozilla's SRP implementation.

I agree, the README could be more clear about the formulas chosen.

**Comment by jackiszhp** [comment]
with your information, now i know the stanford page should be updated to reflect the newest agreement.
