### ISSUE TITLE
M1 calculation differs from Wikipedia

### ISSUE THREAD

**Issue by jgimenez** [alax/jsrp#22]
Hi there, I've found a discrepancy with how the [server library I'm using](https://github.com/getinsomnia/go-srp/blob/master/srp.go#L76) calculates M1.

[Wikipedia](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) defines M1 as:

    Alternatively, in a password-only proof the calculation of K can be skipped and the shared S proven with:
    
    M1 = H(A | B | SCarol)

which seems to be what my library is using.

However, this library seems to be using [M1 = H(A | B | K)](https://github.com/alax/jsrp/blob/master/src/srp.coffee#L168), where [K = H(S)](https://github.com/alax/jsrp/blob/master/src/srp.coffee#L159)

I would like to know where this discrepancy comes from, is it because of different versions of SRP? Thanks!

Related to #15

**Comment by jgimenez** [comment]
Also [Mozilla's implementation](https://github.com/mozilla/node-srp/blob/master/lib/srp.js#L301) seems to be using M1 = H(A | B | S)

**Comment by fcp89** [comment]
Hi,
I had the same issue a while ago with the server-side library "Bouncy Castle".
According to https://tools.ietf.org/html/rfc2945 an "Interleaved SHA" (K) has to be used for proof generation.
So i don't understand why everybody else is using S.
Anyway, to get stuff working I implemented a "compatibility mode" into alax/jsrp back then.
I just commited the code into a fork. If anybody thinks it's useful i can open a pull request.

**Comment by jgimenez** [comment]
Thanks for publishing your patch @fcp89 , I'll probably use it for practical reasons as well, though I'm still intrigued on why this difference. Maybe @alax knows.

**Comment by alax** [comment]
I'm looking over my old notes and I can't seem to find why I chose that calculation over the one specified in the RFC. I was using a combination of the RFC documents, Wikipedia, and Mozilla's implementation, and I think maybe I just got some of the various documents confused and ended up with a hodgepodge calculation.

Since K is the strong session key, computing the proof this way will still provide the strong mutual authentication required (it shouldn't reduce the security at all, in theory), but since it doesn't match the RFC, I'd gladly welcome a pull to make it match the spec.

Thanks!

**Comment by fcp89** [comment]
So, i opened a pull request with an optional mode that uses S instead of K.

I could not find a reliable source that supports wikipedias statement "Alternatively, in a password-only proof the calculation of K can be skipped". Therefore I made it optional instead of replacing it, since this library here also provides public functions to retrieve the shared key.

This will however probably not solve @jgimenez problem. 
I saw that your go-srp library uses a wild mix of S for M1 and K for M2 - which does not seem right.

**Comment by jgimenez** [comment]
Thanks for the PR!

Yup, still my question remains unsolved. I see a wide inconsistency amongst libraries and different papers describing SRP, so I guess the problem is just there's no de facto standard yet. Even papers say things like "one possible way" instead of something along the lines of "this is the standard way it's done".

**Comment by fcp89** [comment]
Completely agree.

**Comment by dangtony98** [comment]
Hey @jgimenez I just ran into this discrepancy between implementations as well that's making it difficult to bridge the two libraries (also looking at Kong/go-srp written in Go) — Were you able to figure a workaround?

**Comment by jgimenez** [comment]
@dangtony98 no, sorry. I ended up not implementing SRP because I couldn't find good documentation, making me feel it's not that widely adopted and well-understood.

**Comment by dangtony98** [comment]
Ah I see. You were correct though that the computation of M1 differs between the two packages — I tried modifying the variable in the Kong package and made it compatible with JSRP. That said, you're right that it's not widely adopted and well-understood.
